name: Build and Deploy to Azure Static Web Apps

on:
  workflow_dispatch:

jobs:
  # フロントエンドビルドジョブ
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/out/
          retention-days: 1

  # APIビルドジョブ
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for API
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install API Dependencies
        working-directory: ./api
        run: npm install

      - name: Build API
        working-directory: ./api
        run: npm run build

      - name: Run API Tests
        working-directory: ./api
        run: npm run test

  # Azure Static Web Appsデプロイジョブ
  deploy-swa:
    needs: [build-frontend, test-api]
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_LOCATION: ${{ vars.APP_LOCATION || 'deploy/frontend' }}
      OUTPUT_LOCATION: ${{ vars.OUTPUT_LOCATION || 'out' }}
      API_LOCATION: ${{ vars.API_LOCATION || 'deploy/api' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./deploy/frontend
      - name: Copy Static Web App Configuration
        run: |
          cp frontend/config/prod/staticwebapp.config.json deploy/frontend/out/staticwebapp.config.json
      - name: check
        working-directory: ./deploy/frontend/out
        run: ls -la

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: "${{ env.OUTPUT_LOCATION }}"
          skip_app_build: true
          skip_api_build: false
