name: Build and Deploy to Azure Static Web Apps

on:
  workflow_dispatch:

jobs:
  # フロントエンドビルドジョブ
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            frontend/out/
            frontend/config/prod/staticwebapp.config.json
          retention-days: 1

  # APIビルドジョブ
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for API
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "api/package-lock.json"

      - name: Install API Dependencies
        working-directory: ./api
        run: npm ci

      - name: Build API
        working-directory: ./api
        run: npm run build

      - name: Upload API Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: |
            api/dist/
            api/host.json
            api/package.json
          retention-days: 1

  # Azure Static Web Appsデプロイジョブ
  deploy-swa:
    needs: [build-frontend, build-api]
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_LOCATION: ${{ vars.APP_LOCATION || 'deploy/api' }}
      OUTPUT_LOCATION: ${{ vars.OUTPUT_LOCATION || 'deploy/out' }}
      API_LOCATION: ${{ vars.API_LOCATION || '' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Frontend Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./deploy/frontend

      - name: Download API Artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-build
          path: ./deploy/api

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
          skip_app_build: true
          skip_api_build: true
